name: 'Set vars to env context'
description: 'Sets variables from vars to env context'

runs:
  using: 'composite'

  steps:
    - name: Set vars to env
      env:
        VARS_JSON: ${{ toJSON(vars) }}
      run: |
        echo "${{ github.action_path }}"
        echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
