name: 'Set vars to env context'
description: 'Sets variables from vars to env context'
author: 'Azeem Sajid'

inputs:
  json:
    description: 'JSON'
    required: false
    default: ''

runs:
  using: 'composite'

  steps:
    - name: Set vars to env
      env:
        JSON: ${{ inputs.json }}
      shell: bash
      run: |
        echo '${{ github.action_path }}'
        echo "$JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
        echo '${{ toJSON(github) }}'
