name: 'Set vars to env context'
description: 'Sets variables from vars to env context'

runs:
  using: 'composite'

  steps:
    - name: Set vars to env
      # env:
      #   VARS_JSON: ${{ toJSON(github.vars) }}
      shell: bash
      run: |
        echo "${{ github.action_path }}"
        echo "${{ toJSON(github) }}"
        echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV
