name: Problem Matcher
description: Problem Matcher

runs:
  using: composite

  steps:
    - name: Set up problem matcher
      env:
        PROBLEM_MATCHER_CONFIG: |
          {
            "problemMatcher": [
              {
                "owner": "xunit",
                "pattern": [ 
                  {
                    "regexp": "^\\s*Failed\\s(.*)$",
                    "message": 1
                  }
                ]
              }
            ]
          }
      shell: bash
      run: |
        echo "$PROBLEM_MATCHER_CONFIG" > xunit.json
        echo "$PWD/xunit.json"
        cat -n "$PWD/xunit.json"
        echo "::add-matcher::$PWD/xunit.json"
