name: Problem Matcher
description: Problem Matcher

runs:
  using: composite

  steps:
    - name: Set up problem matcher
      env:
        PROBLEM_MATCHER_CONFIG: |
          {
            "problemMatcher": [
              {
                "owner": "xunit",
                "pattern": [
                  {
                    "regexp": "^\\s*Failed\\s(.*)([\\s\\S]*?)(Stack\\sTrace:\\s*at\\s)(.*)\\s+in\\s+(.*):line\\s+(\\d+)\\s*$",
                    "message": 2,
                    "fromPath": 5,
                    "file": 5,
                    "line": 6
                  }
                ]
              }
            ]
          }
      shell: bash
      run: |
        echo "$PROBLEM_MATCHER_CONFIG" > xunit.json
        echo "$PWD/xunit.json"
        cat -n "$PWD/xunit.json"
        echo "::add-matcher::$PWD/xunit.json"
