name: assign_with_condition

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      BRANCH1: main
      BRANCH2: develop

    steps:
    - name: Checkout 1
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ env.BRANCH1 == 'main' && '0' || '1' }}

    - name: Checkout 2
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ env.BRANCH2 == 'develop' && '1' || '0' }}
