name: auto_manual_steps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Automatic step
      run: echo "Automatic"

    - name: Manual step
      if: ${{ github.ref_name == 'main' && github.event_name == 'workflow_dispatch' }}
      run: echo "Manual"
