name: shell_test

on:
  workflow_dispatch:

jobs:
  unspecified:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      run: echo '${{ toJson(github) }}'

  sh:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      shell: sh
      run: echo '${{ toJson(github) }}'

  bash:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      shell: bash
      run: echo '${{ toJson(github) }}'
