name: build_with_custom_tests

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    types: [closed]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
    - name: Tests
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Testing..."
        echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "Building..."
        echo "$GITHUB_CONTEXT"
