name: shell_test

on:
  workflow_dispatch:

jobs:
  unspecified:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'unspecified'

  sh:
    runs-on: ubuntu-latest
    steps:
    - shell: sh
      run: |
        echo 'sh'
        ls -l $(which sh)
        dpkg -s dash

  bash:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: echo 'bash'
