name: shell_test

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: unspecified
      run: echo 'unspecified'

    - name: sh
      shell: sh
      run: |
        ls -l $(which sh)
        dpkg -s dash

    - name: bash
      shell: bash
      run: echo 'bash'
