name: build_with_custom_tests

on:
  push:
    branches: ['**']
    tags-ignore: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
    - name: Tests
      run: echo '${{ toJson(github) }}'

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo '${{ toJson(github) }}'
