name: container_secrets

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ${{ secrets.IMAGE }}:latest

    steps:
      - name: Test
        run: echo "Test"
