name: container_secrets

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name
        type: string
        required: false
        default: 'ubuntu'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ['ubuntu']

    # container: #${{ inputs.IMAGE }}:latest
    #   image: ${{ inputs.IMAGE }}:latest

    # container: ${{ vars.IMAGE }}:latest
    #   image: ${{ vars.IMAGE }}:latest

    # container: ${{ secrets.IMAGE }}:latest
    #   image: ${{ secrets.IMAGE }}:latest

    # env:
    #   IMAGE: ubuntu

    container: ${{ matrix.image }}:latest
    #   image: ${{ env.IMAGE }}:latest
    #   image: ${{ env.IMAGE }}:latest

    steps:
      - name: Test
        run: |
          echo "Test"
          echo '${{ toJson(strategy) }}' >> "$GITHUB_STEP_SUMMARY"
