name: custom_checkout

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Check branches
      run: |
        git branch
        git branch -a
        git checkout develop
