name: conatiner_services

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    container: ubuntu:latest

    steps:
      - name: Check
        run: |
          sudo apt install -y mysql-client
          mysql --host db --port 3306 -uroot -ppassword -e 'SHOW DATABASES;'
