name: container_secrets

on:
  workflow_dispatch:
    inputs:
      description: image name
      type: string
      required: false
      default: 'ubuntu'

env:
  IMAGE: ubuntu

jobs:
  build:
    runs-on: ubuntu-latest

    container: ${{ vars.IMAGE }}:latest
    # container: ${{ env.IMAGE }}:latest
    #   image: ${{ env.IMAGE }}:latest

    # container: ${{ secrets.IMAGE }}:latest
    #   image: ${{ secrets.IMAGE }}:latest

    steps:
      - name: Test
        run: echo "Test"
