name: conatiner_services

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
            - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container: ubuntu:latest

    steps:
      - name: Install postgresql-client (psql)
        run: |
          apt update -y
          apt install -y postgresql-client
          psql --version

      - name: Check DB connection
        run: |
          psql "postgresql://postgres:postgres@postgres:5432" <<EOF
            CREATE TABLE test (id INT);
            INSERT INTO test (id) VALUES (123);
            INSERT INTO test (id) VALUES (456);
            INSERT INTO test (id) VALUES (789);
            SELECT * FROM test;
          EOF
