name: changed_files_test

on: workflow_dispatch

jobs:
  changed-files:
    runs-on: ubuntu-latest

    outputs:
      py: ${{ steps.changed-files-py.outputs.all_changed_files }}
      sh: ${{ steps.changed-files-sh.outputs.all_changed_files }}
      yaml: ${{ steps.changed-files-yaml.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Touch files and add commit
        run: |
          touch test123.{py,sh,yml,yaml} test456.{py,sh,yml,yaml}
          git config --global user.name "Azeem Sajid"
          git config --global user.email "azeem.sajid@gmail.com"
          git add .
          git commit -m "Touch files"

      - name: Changed files (py)
        id: changed-files-py
        uses: tj-actions/changed-files@v46
        with:
          files: '**.py'

      - name: Changed files (sh)
        id: changed-files-sh
        uses: tj-actions/changed-files@v46
        with:
          files: '**.sh'

      - name: Changed files (cpp)
        id: changed-files-yaml
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **.yml
            **.yaml

  lint:
    runs-on: ubuntu-latest
    needs: [changed-files]
    steps:
      - name: Check
        run: |
          echo 'py: ${{ needs.changed-files.outputs.py }}'
          echo 'sh: ${{ needs.changed-files.outputs.sh }}'
          echo 'yaml: ${{ needs.changed-files.outputs.yaml }}'
