name: container_secrets

on: workflow_dispatch

env:
  IMAGE: ubuntu

jobs:
  build:
    runs-on: ubuntu-latest

    container: ${{ env.IMAGE }}:latest
      # image: ${{ env.IMAGE }}:latest

    steps:
      - name: Test
        run: echo "Test"
