name: dynamic_context_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check
      env:
        # GITHUB: ${{ format('{0}', 'github') }}
        html_url: github.event.[github.event_name].html_url
      run: |
        echo "$html_url"
