name: double_checkout_docker_build

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout test
      uses: actions/checkout@v5
      with:
        path: repoA

    - name: Check test
      run: pwd && ls -Gghl

    - name: Checkout iamazeem/cwm-keda-external-scaler
      uses: actions/checkout@v5
      with:
        repository: iamazeem/cwm-keda-external-scaler
        path: repoB

    - name: Check iamazeem/cwm-keda-external-scaler
      run: pwd && ls -Gghl

    - name: Build iamazeem/cwm-keda-external-scaler
      uses: docker/build-push-action@v6
      with:
        context: ./repoB
        tags: iamazeem/cwm-keda-external-scaler:latest
