name: dynamic_secrets

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: |
        secrets="$(jq -c <<< '${{ toJson(secrets) }}')"
        for secret in SECRET1 SECRET2; do
          k="$secret"
          v="$(jq ".$key" <<< "$secrets" | sed 's|.|& |g')"
          echo "$k: $v"
        done
