name: delete_workflow_runs_action_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Delete
      uses: iamazeem/delete-workflow-runs-action@03dc53debeaf098615ca7b5f0fc795c61ae3434d
      with:
        workflow: ci workflow with spaces.yml
        keep: 1
