name: dynamic_secrets

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check
      env:
        SECRETS: '${{ toJson(secrets) }}'
      run: |
        for secret in SECRET1 SECRET2; do
          valye="$(jq --arg key "$secret" '.$key' <<< "$SECRETS" | sed 's|.|& |g')"
          echo "$secret: $value"
        done
