name: dump_contexts

on: workflow_dispatch

jobs:
  dump:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Dump contexts
        run: |
          {
            echo '### `github` context'
            echo '```json'
            echo '${{ toJson(github) }}'
            echo '```'

            echo '### `env` context'
            echo '```json'
            echo '${{ toJson(env) }}'
            echo '```'

            echo '### `vars` context'
            echo '```json'
            echo '${{ toJson(vars) }}'
            echo '```'

            echo '### `runner` context'
            echo '```json'
            echo '${{ toJson(runner) }}'
            echo '```'

            echo '### `job` context'
            echo '```json'
            echo '${{ toJson(job) }}'
            echo '```'

            echo '### `secrets` context'
            echo '```json'
            echo '${{ toJson(secrets) }}'
            echo '```'

            echo '### `steps` context'
            echo '```json'
            echo '${{ toJson(steps) }}'
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
