name: dynamic_secrets

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set env var
      run: |
        {
          echo "key1=SECRET1"
          echo "key2=SECRET2"
        } >>"$GITHUB_ENV"

    - name: Check
      env:
        SECRET1: ${{ secrets[env.key1] }}
        SECRET2: ${{ secrets[format('{0}', env.key2)] }}
      run: |
        echo "SECRET1: $(echo "$SECRET1" | sed 's|.|& |g')"
        echo "SECRET1: $(echo "$SECRET2" | sed 's|.|& |g')"

    - name: Check with jq
      env:
        SECRETS: '${{ toJson(secrets) }}'
      run: |
        for secret in SECRET1 SECRET2; do
          value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS" | sed 's|.|& |g')"
          echo "$secret: $value"
        done
