name: dynamic_context_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check
      env:
        GITHUB: ${{ format('github.event.{0}.html_url', github.event_name) }}
      run: |
        echo '${{ env.GITHUB }}'
