name: env_files

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set
        id: set
        run: |
          echo 'TEST=123' >> "$GITHUB_ENV"
          echo 'TEST=123' >> "$GITHUB_OUTPUT"
          echo 'TEST=123' >> "$GITHUB_STEP_SUMMARY"

      - name: Get
        run: |
          cat "$GITHUB_ENV" || true
          cat "$GITHUB_OUTPUT" || true
          cat "$GITHUB_SETP_SUMMARY" || true
