name: env_test

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Create file
      env:
        TEMPLATE: |
          {
            "version": "${VERSION}",
            "instance": "${INSTANCE}"
          }
      shell: bash
      run: |
        echo "$TEMPLATE" > template.json
        cat template.json

    - name: Replace env vars
      uses: danielr1996/envsubst-action@1.0.0
      env:
          VERSION: 1.2.3
          INSTANCE: staging
      with:
        input: template.json
        output: deployment.json
    
    - name: Check
      run: cat template.json
