name: freebsd_deprecations

on: workflow_dispatch

env:
  TEST: test123

jobs:
  freebsd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up FreeBSD
      uses: cross-platform-actions/action@v1.1.0
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh
        environment_variables: TEST ENV_VAR_1

    - name: Run
      env:
        ENV_VAR_1: env_var_1
      shell: cpa.sh {0}
      run: |
        echo "TEST: $TEST"
        echo "ENV_VAR_1: $ENV_VAR_1"

    - name: Run script
      shell: cpa.sh {0}
      run: |
        ./scripts/print-env-var.sh
