name: freebsd_env_vars

on: workflow_dispatch

env:
  VAR_WORKFLOW: var_workflow

jobs:
  freebsd:
    runs-on: ubuntu-latest

    env:
      VAR_JOB: var_job

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up FreeBSD
      uses: iamazeem/cross-platform-actions-action@145-propagate-env-vars
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh

    - name: Check with cap.sh
      env:
        VAR_STEP: var_step
        VAR_STEP_MULTILINE: |-
          Hello,
          World!
      shell: cpa.sh {0}
      run: |
        echo "VAR_WORKFLOW: $VAR_WORKFLOW"
        echo "VAR_JOB: $VAR_JOB"
        echo "VAR_STEP: $VAR_STEP"
        echo "VAR_STEP_MULTILINE: $VAR_STEP_MULTILINE"
