name: freebsd_deprecations

on: workflow_dispatch

# env:
#   TEST: test123

jobs:
  freebsd:
    runs-on: ubuntu-latest

    # env:
    #   VAR_1: var_1

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up FreeBSD
      uses: cross-platform-actions/action@v1.3.0
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh
        # environment_variables: TEST ENV_VAR_1 VAR_1

    # - name: Run
    #   env:
    #     ENV_VAR_1: env_var_1
    #   shell: cpa.sh {0}
    #   run: |
    #     echo "TEST: $TEST"
    #     echo "ENV_VAR_1: $ENV_VAR_1"
    #     echo "VAR_1: $VAR_1"

    # - name: Run script
    #   shell: cpa.sh {0}
    #   run: |
    #     ./scripts/print-env-var.sh

    - name: Set
      shell: cpa.sh {0}
      run: |
        echo "TEST_VAR=test_123" >> "$GITHUB_ENV"

    - name: Get
      run: |
        echo "TEST_VAR=$TEST_VAR"

    - name: Check
      run: |
        echo "GITHUB_ENV: $GITHUB_ENV"
        echo "==="
        cat "$GITHUB_ENV"
        echo "==="
        cat "$GITHUB_ENV" | jq .

    - name: Env
      env:
        TEST_VAR_1: test_var_1
        TEST_VAR_2: test_var_2
      run: |
        env
