name: git_tag_contents_body

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: py-pdf/pypdf

    - name: Set
      run: |
        git fetch --tags --force
        latest_tag=$(git describe --tags --abbrev=0)
        echo "latest_tag: $latest_tag"
        echo
        tag_body="$(git tag -l "$latest_tag" --format='%(contents:body)')"
        echo "tag_body: $tag_body"
        echo
        echo "tag_body<<EOF" >> "$GITHUB_ENV"
        echo "$tag_body" >> "$GITHUB_ENV"
        echo "EOF" >> "$GITHUB_ENV"

    - name: Get
      env:
        tag_body: '${{ env.tag_body }}'
      run: |
        echo "tag_body: $tag_body"
