name: gh_cli_variable_matrix

on: workflow_dispatch

jobs:
  set:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        value: [1, 2, 3]

    env:
      GITHUB_TOKEN: ${{ secrets.GH_VARIABLE_PAT }}
      VAR: VAR_${{ github.run_id }}
      VAL: ${{ matrix.value }}

    steps:
      - uses: actions/checkout@v4

      - run: gh auth status
      - run: gh variable delete "$VAR" || true
      - run: gh variable set "$VAR" --body "$VAL"
      - run: gh variable list

  get:
    needs: set
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     value: ${{ fromJson(toJson(vars)) }}

    steps:
    - run: echo '${{ toJson(vars) }}'
    - run: echo '${{ format('"{0}"', join(vars.*, '", "')) }}'
