name: gh_cli_variable_matrix

on: workflow_dispatch

jobs:
  set:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        value: [1, 2, 3]

    env:
      GITHUB_TOKEN: ${{ secrets.GH_VARIABLE_PAT }}

    steps:
      - uses: actions/checkout@v4

      - run: gh auth status
      - run: gh variable delete ${{ matrix.value }} || true
      - run: gh variable set 'VAR_${{ github.job }}' --body '${{ matrix.value }}'
      - run: gh variable list

  get:
    needs: set
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     value: ${{ fromJson(toJson(vars)) }}

    steps:
    - run: echo '${{ toJson(vars) }}'
