name: github_script_hash_files_test

on: workflow_dispatch

jobs:
  hash:
    runs-on: ubuntu-latest

    outputs:
      result: '${{ steps.hash.outputs.result }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hash
        id: hash
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            return glob.hashFiles('**/README.md');

  check:
    runs-on: ubuntu-latest
    needs: [hash]

    steps:
      - name: Check
        env:
          HASH: '${{ needs.hash.outputs.result }}'
        run: |
          echo "HASH: [$HASH]"
