name: git_tag

on: workflow_dispatch

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - run: |
        ts=$(date +%s%3N)
        tag="test-$ts"
        echo create tag "$tag"
        git tag "$tag"
        git push -f origin "$tag"
