name: git_tag_contents_body

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: py-pdf/pypdf

    - name: Set
      run: |
        git fetch --tags --force
        latest_tag=$(git describe --tags --abbrev=0)
        echo "latest_tag: $latest_tag"
        echo
        tag_body="$(git tag -l "$latest_tag" --format='%(contents:body)')"
        echo "tag_body: $tag_body"
        echo
        echo "tag_body=$tag_body" >> "$GITHUB_ENV"

    - name: Get
      run: |
        echo "${{ env.tag_body }}"