name: gh_cli_variable_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    # environment: Dev

    env:
      GITHUB_TOKEN: ${{ secrets.GH_VARIABLE_PAT }}
      TEST_VAR: 'test_var_value'
      TEST_VAR_ENV: 'test_var_value_env'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete
        run: |
          gh variable delete TEST_VAR || true
          # gh variable delete TEST_VAR_ENV --env Dev

      - name: List (repo)
        run: gh variable list

      # - name: List (env Dev)
      #   run: gh variable list --env Dev

      - name: Set (repo)
        run: gh variable set TEST_VAR --body "$TEST_VAR"

      # - name: Set (env Dev)
      #   run: gh variable set TEST_VAR_ENV --body "$TEST_VAR_ENV" --env Dev

      - name: List (repo)
        run: gh variable list

      # - name: List (env Dev)
      #   run: gh variable list --env Dev

      - name: Dump
        run: |
          echo 'TEST_VAR: ${{ vars.TEST_VAR }}'
          # echo 'TEST_VAR_ENV: ${{ vars.TEST_VAR_ENV }}'
