name: gh_cli_variable_matrix

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GH_VARIABLE_PAT }}

jobs:
  set:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: [repo1, repo2, repo3]

    env:
      VAR: VAR_${{ matrix.repo }}
      VAL: ${{ format('["{0}/tag1", "{0}/tag2"]', matrix.repo) }}

    steps:
      - uses: actions/checkout@v4

      - run: gh auth status
      - run: gh variable delete "$VAR" || true
      - run: gh variable set "$VAR" --body "$VAL"
      - run: gh variable list

  get:
    needs: set
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     value: ${{ fromJson(toJson(vars)) }}

    steps:
    - run: gh auth status
    - run: gh variable list

    - run: echo '${{ toJson(vars) }}'
    - run: echo '${{ join(vars.*) }}'
    - run: echo '${{ format('"{0}"', join(vars.*, '", "')) }}'
