name: hash_files_test

on: workflow_dispatch

env:
  DIR: files

jobs:
  hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Hash [actions/github-script]
        uses: actions/github-script@v7
        env:
          DIR: ${{ env.DIR }}
        with:
          result-encoding: string
          script: |
            const hash = await glob.hashFiles('test.json', 'hash-test/' + process.env.DIR);
            console.log(hash);

      - name: Hash [hashFiles + env var]
        env:
          FILE: hash-test/${{ env.DIR }}/test.json
        run: echo "${{ hashFiles(env.FILE) }}"

      - name: Hash [hashFiles + format]
        env:
          HASH: ${{ hashFiles(format('hash-test/{0}/test.json', env.DIR)) }}
        run: echo "$HASH"

      - name: Hash [hashFiles + join]
        env:
          FILE: ${{ join(fromJson('["hash-test", env.DIR, "test.json"]'), '/') }}
          HASH: ${{ hashFiles(join(fromJson('["hash-test", env.DIR, "test.json"]'), '/')) }}
        run: echo "$FILE | $HASH"
