name: hash_files_test

on: workflow_dispatch

env:
  DIR: files

jobs:
  hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Hash [actions/github-script]
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const path = 'hash-test/' + process.env.DIR + '/test.json';
            const hash = await glob.hashFiles(path);
            console.log(hash);

      - name: Hash [hashFiles + *]
        run: echo "${{ hashFiles('hash-test/*/test.json') }}"

      - name: Hash [hashFiles + **]
        run: echo "${{ hashFiles('hash-test/**/test.json') }}"

      - name: Hash [hashFiles + env var]
        env:
          FILE: hash-test/${{ inputs.DIR }}/test.json
        run: echo "${{ hashFiles(env.FILE) }}"

      - name: Hash [hashFiles + format]
        env:
          HASH: ${{ hashFiles(format('hash-test/{0}/test.json', env.DIR)) }}
        run: echo "$HASH"
