name: install_oracle_instant_client

on: workflow_dispatch

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Create setup script
      run: |
        pwd
        mkdir scripts
        cd scripts
        cat >init.sql <<EOF
          ALTER SESSION SET CONTAINER = FREEPDB1;
          CREATE USER test IDENTIFIED BY test QUOTA UNLIMITED ON USERS;
          GRANT CONNECT, RESOURCE TO test;
          GRANT CREATE TABLE TO test;
          ALTER SESSION SET CURRENT_SCHEMA = test;
          CREATE TABLE Test
          (
            ID INT
          );
          INSERT INTO Test (ID) VALUES(123);
          INSERT INTO Test (ID) VALUES(456);
          SELECT ID FROM Test;
        EOF
        cat init.sql

    - name: Setup Oracle container
      uses: gvenzl/setup-oracle-free@v1
      with:
        container-runtime: docker
        app-user: app_user
        app-user-password: app_user_password
        setup-scripts: ${{ github.workspace }}/scripts

    - name: Check Oracle container logs for errors
      run: |
        docker container ls
        docker container logs oracledb | tee /tmp/oracledb.log
        if grep 'ERROR' /tmp/oracledb.log >/dev/null; then
          echo "[ERR] Something went wrong!"
          echo "[ERR] See above logs for more details."
          exit 1
        fi

    - name: Install Oracle Instant Client (OIC)
      run: |
        echo "RUNNER_OS: $RUNNER_OS"
        echo "RUNNER_ARCH: $RUNNER_ARCH"

        if [[ $RUNNER_OS == "Linux" && $RUNNER_ARCH == "X64" ]]; then
          echo "[INF] Installing on Linux..."

          URLS=(
            https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip
            https://download.oracle.com/otn_software/linux/instantclient/instantclient-sqlplus-linuxx64.zip
          )

          for URL in "${URLS[@]}"; do
            echo "[INF] Downloading... [$URL]"
            wget -q "$URL"
          done

          INSTALL_BASE_DIR="$GITHUB_WORKSPACE/oracle-instantclient"

          for ZIP in instantclient-*.zip; do
            unzip -q -o "$ZIP" -d "$INSTALL_BASE_DIR"
          done

          INSTALL_DIR_PATH="$(realpath "$INSTALL_BASE_DIR"/instantclient_*)"
          tree "$INSTALL_DIR_PATH"

          echo "[INF] Setting path... [$INSTALL_DIR_PATH]"
          echo "$INSTALL_DIR_PATH" >> "$GITHUB_PATH"

          echo "$INSTALL_DIR_PATH" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig

          echo "[INF] Installed successfully!"
        elif [[ $RUNNER_OS == "macOS" && $RUNNER_ARCH == "X64" ]]; then
          echo "[INF] Installing on macOS..."
        elif [[ $RUNNER_OS == "Windows" && $RUNNER_ARCH == "X64" ]]; then
          echo "[INF] Installing on Windows..."
        else
          echo "[ERR] Unsupported OS and/or architecture!"
          exit 1
        fi

    - name: Check OIC
      run: |
        whereis sqlplus
        sqlplus -V
        sqlplus -s test/test@localhost:1521/FREEPDB1 <<< "SELECT * FROM Test;"
