name: issue_close_on_open

on:
  issues:
    types:
    - opened

jobs:
  close-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
    - name: Close
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        ISSUE: ${{ github.event.issue.number }}
      run: gh issue close --repo "$REPO" --comment "Autoclosing issue $ISSUE" "$ISSUE"
