name: just_pwsh

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up just
      uses: taiki-e/install-action@just

    - name: Set up justfile
      run: |
        cat > justfile << 'EOF'
        set shell := ["pwsh", "-c"]
        hello:
            echo "Hello!"
        EOF
        {
          echo '```shell'
          cat justfile
          echo '```' 
        } | tee -a "$GITHUB_STEP_SUMMARY"

    - name: Run just
      run: |
        {
          echo '```shell'
          just -l
          just
          echo '```'
        } | tee -a "$GITHUB_STEP_SUMMARY"
