name: just_pwsh

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up just
      uses: taiki-e/install-action@just

    - name: Set up justfile
      shell: bash
      run: |
        cat > justfile << 'EOF'
        set shell := ["pwsh", "-c"]
        hello:
          Write-Output "Hello!"
        EOF
        {
          echo '```shell'
          cat justfile
          echo '```' 
        } | tee -a "$GITHUB_STEP_SUMMARY"

    - name: Run just (Bash)
      shell: bash
      run: |
        {
          echo '```shell'
          just -l
          just
          echo '```'
        } | tee -a "$GITHUB_STEP_SUMMARY"

    - name: Run just (pwsh)
      shell: pwsh
      run: |
        just -l
        just
