name: java-pkg-publish

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry
      - name: Publish Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cd java/test
          mvn package --batch-mode
          java -cp target/test-1.0.jar test.Test
          mvn deploy:deploy-file --batch-mode \
            -DgroupId=test -DartifactId=test \
            -Dversion=1.0 \
            -Dfile=target/test-1.0.jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository }}
