name: job_id_and_name

on: workflow_dispatch

env:
  REPO: ${{ github.repository }}
  GH_TOKEN: ${{ github.token }}
  RUN_ID: ${{ github.run_id }}
  JOB_ID: ${{ github.job }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        echo "JOB_ID: $JOB_ID"
        JOB_NAME="$(gh run view --repo $REPO --json jobs --jq '.jobs[0].name' $RUN_ID)"
        echo "JOB_NAME: $JOB_NAME"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "JOB_ID: $JOB_ID"
        JOB_NAME="$(gh run view --repo $REPO --json jobs --jq '.jobs[0].name' $RUN_ID)"
        echo "JOB_NAME: $JOB_NAME"
