name: jobs_and_workflow_logs

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "Testing..."

  logs:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Logs
      env:
        GITHUB_TOKEN: ${{ github.token }}
        RUN_ID: ${{ github.run_id }}
      run: |
        gh run view "$RUN_ID" --log --repo iamazeem/test
