name: keda_deployment

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'Timeout'
        default: '10m'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check minikube
      run: |
        minikube version
        minikube start
        minikube status

    - name: Deploy KEDA
      env:
        TIMEOUT: ${{ inputs.timeout }}
      run: |
        eval "$(minikube -p minikube docker-env)"
        KUBECTL="minikube kubectl --"
        echo "kubectl version:"
        $KUBECTL version

        KEDA_DEPLOYMENT="https://github.com/kedacore/keda/releases/download/v2.1.0/keda-2.1.0.yaml"

        echo "Set up keda"
        $KUBECTL apply -f $KEDA_DEPLOYMENT

        KEDA_NAMESPACE="keda"
        KEDA_DEPLOYMENTS=("keda-operator" "keda-metrics-apiserver")
        for deployment in "${KEDA_DEPLOYMENTS[@]}"; do
            echo "Waiting for deployment/$deployment to be ready"
            if ! $KUBECTL -n $KEDA_NAMESPACE rollout status --timeout=$TIMEOUT "deployment/$deployment"; then
              $KUBECTL -n $KEDA_NAMESPACE get pods
              exit 1
            fi
        done

        echo "SUCCESS: keda is ready!"
