name: matrix_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [1, 2]
    steps:
      - name: Step ${{ matrix.step }}
        run: echo 'Step ${{ matrix.step }}'

  wait:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: echo 'Waiting...'
