name: matrix_job_outputs

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [1, 2]
    outputs:
      VALUE: ${{ steps.set.outputs.VALUE }}
    steps:
    - name: Step [matrix.value=${{ matrix.value }}]
      id: set
      env:
        VALUE: ${{ matrix.value }}
      run: |
        echo "VALUE=$VALUE" | tee -a "$GITHUB_OUTPUT"

  check:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
    - name: Check
      env:
        VALUE: ${{ needs.matrix.outputs.VALUE }}
      run: |
        echo "VALUE=$VALUE"
