name: matrix_jobs

on: workflow_dispatch

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
    - name: Step 1
      run: sleep 5
    - name: Step 2
      run: |
        sleep 5
        if [[ $RUNNER_OS == 'Windows' ]]; then
          sleep 5
          exit 1
        fi
    - name: Step 3
      run: sleep 5

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
    - name: Step 1
      run: sleep 5
    - name: Step 2
      run: sleep 5
    - name: Step 3
      run: |
        sleep 5
        if [[ $RUNNER_OS == 'Windows' ]]; then
          sleep 5
          exit 1
        fi

  publish:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
    - name: Step 1
      run: |
        sleep 5
        if [[ $RUNNER_OS == 'Windows' ]]; then
          sleep 5
          exit 1
        fi
    - name: Step 2
      run: sleep 5
    - name: Step 3
      run: sleep 5
