name: matrix_shell_test

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        shell: [sh, bash]

    runs-on: ubuntu-latest

    steps:
    - name: Test (${{ matrix.job.name }})
      shell: '${{ matrix.job.shell }}'
      run: |
        echo "Test"
