name: mariadb_services

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - "3306:3306"
        env:
          MARIADB_DATABASE: db
          MARIADB_USER: root
          MARIADB_PASSWORD: password
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_MYSQL_LOCALHOST_USER:
          # MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Show DBs
        run: mysql --host 127.0.0.1 -uroot -ppassword -e "SHOW DATABASES;"
