name: MySQL Import Test

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    services:
      mysql:
        # https://hub.docker.com/_/mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Import MySQL file
      run: |
        mysql --host 127.0.0.1 --port 33306 -uroot -ppassword -e "SHOW DATABASES LIKE 'test'"
        # mysql --user=user --password=password --database=test --host=127.0.0.1 --port=33306 -e "SHOW DATABASES LIKE 'test'"
        # mysql $ARGS < request_data.sql
