name: mariadb_services

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - "3306:3306"
        env:
          MARIADB_DATABASE: db
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Show DBs
        run: mysql --host 127.0.0.1 -uuser -ppassword -e "SHOW DATABASES;"
