name: matrix_jobs

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
    - name: Test
      run: |
        sleep 5s
        [[ $RUNNER_OS == 'Windows' ]] && exit 1
