name: matrix_test

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        step: [1, 2, 3]
    steps:
      - name: Step ${{ matrix.step }}
        env:
          STEP: '${{ matrix.step }}'
        run: |
          echo "Step $STEP"
          if [[ $STEP == '2' ]]; then
            exit 1
          fi

  pass:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Pass
        run: exit 0

  fail:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Fail
        run: exit 1

  wait:
    needs: [matrix, pass, fail]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: echo 'Waiting...'
