name: matrix_jobs

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
    - name: Step 1
      run: sleep 10
    - name: Step 2
      run: sleep 10
    - name: Step 3
      run: |
        sleep 10
        if [[ $RUNNER_OS == 'Windows' ]]; then
          sleep 5
          exit 1
        fi
