name: MySQL Import Test

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    services:
      mysql:
        # https://hub.docker.com/_/mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Import MySQL file
      env:
        SQL: |
          SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
          START TRANSACTION;
          SET time_zone = "+00:00";
          CREATE TABLE `table` (
            `id` int(11) NOT NULL,
            `name` varchar(255) NOT NULL,
            `email` varchar(255) NOT NULL
          );
          INSERT INTO `table` (`id`, `name`, `email`)
          VALUES
            (111, 'abc', 'abc@email.com'),
            (222, 'def', 'def@email.com'),
            (333, 'ghi', 'ghi@email.com'),
            (444, 'jkl', 'jkl@email.com');
          ALTER TABLE `table` ADD PRIMARY KEY (`id`);
          COMMIT;
      run: |
        mysql --host 127.0.0.1 --port 33306 -uroot -ppassword -e "SHOW DATABASES LIKE 'test'"
        echo "$SQL" > test.sql
        echo "--- SQL ---"
        cat test.sql
        echo "--- --- ---"
        mysql --host 127.0.0.1 --port 33306 -uroot -ppassword test < test.sql
