name: matrix_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        step: [1, 2]
    steps:
      - name: Pass Step 1
        env:
          STEP: '${{ matrix.step }}'
        run: |
          echo "Step $STEP"

      - name: Fail Step 2
        env:
          STEP: '${{ matrix.step }}'
        run: |
          echo "Step $STEP"
          [[ $STEP == '2' ]] && exit 1

  wait:
    needs: [ci]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: echo 'Waiting...'
