name: macos_15_intel_and_arm64

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-15-intel, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check
      run: echo '${{ runner.arch }} | ${{ runner.os }} | ${{ runner.name }}'

    - name: Install zsv
      run: |
        brew update
        brew install zsv

    - name: zsv version
      run: zsv version
