name: matrix_jobs

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
    - name: Test
      run: |
        if [[ $RUNNER_OS == 'Windows' ]]; then
          sleep 10
          exit 1
        else
          sleep 5
          exit 0
        fi
