name: matrix_test

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        step: [1, 2]
    steps:
      - name: Step ${{ matrix.step }}
        env:
          STEP: '${{ matrix.step }}'
        run: |
          echo "Step $STEP"
          if [[ $STEP == '2' ]]; then
            exit 1
          fi

  skip:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Skip
        run: exit 0

  pass:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Pass
        run: exit 0

  fail:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Fail
        run: exit 1

  wait:
    needs: [matrix, skip, pass, fail]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: |
          echo 'Waiting...'
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          echo '${{ toJson(needs) }}' >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
