name: matrix_exclusion

on:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        step: [1, 2]

    runs-on: ubuntu-latest

    steps:
    - name: ${{ matrix.step }}
      run: |
        echo "Running step: ${{ matrix.step }}'

    - name: ${{ matrix.step }}
      if: github.ref_name == 'main' && matrix.step == 2
      run: |
        echo "Running step: ${{ matrix.step }}'
