name: MySQL Import Test

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Import MySQL file
      run: |
        echo "Restarting MySQL"
        sudo service mysql restart
        echo "Checking databases"
        mysql --user=user --password=password --database=test -e "SHOW DATABASES LIKE 'test'"
        # mysql $ARGS < request_data.sql
