name: matrix_test

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        value: [1, 2, 3]
    outputs:
      status: ${{ steps.status.outputs.status }}
    steps:
      - name: Step
        env:
          VALUE: '${{ matrix.value }}'
        run: |
          [[ $VALUE == '1' ]] 

      - name: Status
        if: failure()
        id: status
        env:
          MATRIX_VALUE: ${{ matrix.value }}
        run: echo "$GITHUB_JOB.$GITHUB_RUN_ID=$MATRIX_VALUE" >> "$GITHUB_OUTPUT"

  skip:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: exit 0

  pass:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: exit 0

  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1

  status:
    needs: [matrix, skip, pass, fail]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Status
        run: |
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          echo '${{ toJson(needs) }}' >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
