name: os_matrix_from_inputs

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        required: true
        type: boolean
      macos:
        required: true
        type: boolean
      windows:
        required: true
        type: boolean

jobs:
  ci:
    # strategy:
    #   matrix:
    #     os: ${{ fromJson(format('[{0}{1}{2}]', 'ubuntu-latest', '', '')) }}
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: |
        echo '${{ format('[{0}{1}{2}]', 'ubuntu-latest', '', '') }}'
        echo
        echo '${{ fromJson(format('[{0}{1}{2}]', 'ubuntu-latest', '', '')) }}'
        echo
        echo '${{ toJson(fromJson(format('[{0}{1}{2}]', 'ubuntu-latest', '', ''))) }}'
