name: os_matrix_from_inputs

on:
  workflow_dispatch:
    inputs:
      os:
        description: Select OS
        type: choice
        options:
        - "ubuntu-latest"
        - "windows-latest"
        - "macos-latest"
        - ubuntu-latest, macos-latest, windows-latest
        default: ubuntu-latest
        required: true

jobs:
  ci:
    # strategy:
    #   matrix:
    #     os: ${{ fromJson(format('[{0}{1}{2}]', 'ubuntu-latest', '', '')) }}
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
    - name: Check
      env:
        OS: ${{ format('[{0}]', inputs.os) }}
        OS_JSON: ${{ fromJson(format('[{0}]', inputs.os)) }}
      run: |
        echo "$OS"
        echo "$OS_JSON"
