name: os_matrix_from_inputs

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        required: true
        type: boolean
      macos:
        required: true
        type: boolean
      windows:
        required: true
        type: boolean

jobs:
  ci:
    # strategy:
    #   matrix:
    #     os: ${{ fromJson(format('[{0}{1}{2}]', 'ubuntu-latest', '', '')) }}
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
    - name: Check
      env:
        TEST: ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
      run: |
        echo "$TEST"