name: os_matrix_from_inputs

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        required: true
        type: boolean
      macos:
        required: true
        type: boolean
      windows:
        required: true
        type: boolean
  

jobs:
  ci:
    strategy:
      matrix:
        os:
        - ${{ inputs.ubuntu && 'ubuntu-latest' || null }}
        - ${{ inputs.macos && 'macos-latest' || null }}
        - ${{ inputs.windows && 'windows-latest' || null }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: matrix.os
      run: echo '${{ matrix.os }}'
