name: octopus_cli_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Install Octopus CLI 🐙
      # uses: OctopusDeploy/install-octopus-cli-action@v3
      # with:
      #   version: '*'
      run: |
        curl -L https://github.com/OctopusDeploy/cli/raw/main/scripts/install.sh | bash

    - name: Deploy
      env:
        OCTOPUS_URL: '${{ secrets.OCTOPUS_URL }}'
        OCTOPUS_API_KEY: '${{ secrets.OCTOPUS_API_KEY }}'
        OCTOPUS_SPACE: '${{ secrets.OCTOPUS_SPACE }}'
        OCTOPUS_PROJECT: '${{ secrets.OCTOPUS_PROJECT }}'
        OCTOPUS_CHANNEL: '${{ secrets.OCTOPUS_CHANNEL }}'
      run: |
        octopus release list --project="$OCTOPUS_PROJECT"
        octopus release create --project="$OCTOPUS_PROJECT" --release-notes="New Release [$GITHUB_SHA]"
