name: os_matrix_from_inputs

on:
  workflow_dispatch:
    inputs:
      os:
        description: Select OS
        type: choice
        options:
        - '["ubuntu-latest"]'
        - '["windows-latest"]'
        - '["macos-latest"]'
        - '["ubuntu-latest", "macos-latest", "windows-latest"]'
        default: '["ubuntu-latest"]'
        required: true

jobs:
  ci:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check
      run: echo '${{ inputs.os }} | ${{ matrix.os }}'
