name: os_matrix_from_inputs_boolean

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: Ubuntu
        type: boolean
        required: true
        default: true
      macos:
        description: MacOS
        type: boolean
        required: false
        default: false
      windows:
        description: Windows
        type: boolean
        required: false
        default: false

jobs:
  ci:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    #     exclude: ${{ fromJson('["macos-latest", "windows-latest"]') }}
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
    - name: Check
      run: echo "${{ toJson(inputs) }}"
