name: populate_matrix_from_json_for_jobs

on: workflow_dispatch

env:
  VERSIONS: '["9.0.0", "11.0.0"]'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs: 
      all_versions: ${{ steps.step1.outputs.matrix }}
    steps: 
      - name: Create Matrix Variable
        id: step1
        run: echo "matrix=$(jq -cr '@json' <<< '${{ env.VERSIONS }}')" >> $GITHUB_OUTPUT
        # run: echo "matrix=${{ env.VERSIONS }}" >> $GITHUB_OUTPUT

      - name: Check
        run: echo '${{ steps.step1.outputs.matrix }}'

  deploy-gke:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    strategy: 
      matrix: 
        version: ${{ fromJSON(needs.prepare-matrix.outputs.all_versions) }}
    steps:
     - name: Test [${{ matrix.version }}]
       run: echo "${{ matrix.version }}"
