name: pwsh_env_var_test

on: workflow_dispatch

jobs:
  job:
    runs-on: windows-latest

    steps:
      - name: Shell version
        run: pwsh --version

      - name: Set
        env:
          REF: "v1.0.0"
        run: |
          $TAG = $env:REF.TrimStart("v")
          echo "TAG=$TAG" >> $env:GITHUB_ENV

      - name: Get
        run: echo "TAG=$env:TAG"
