name: python_playsound_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        mkdir test && cd test
        echo 'playsound==1.3.0' > requirements.txt

        python --version
        pip --version

        python -m pip install --upgrade pip
        pip install --upgrade wheel
        pip install -r requirements.txt
