name: python_version_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.2'

    - name: Check Python version
      run: |
        python --version
        python3 --version
