name: pr_event_test

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check pull_request event
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo '${{ toJSON(github) }}' | tee -a "$GITHUB_STEP_SUMMARY"
