name: php_container

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      php:
        image: php:7.4.33-apache-bullseye
        ports:
        - 80:80
    steps:
    - name: Test
      run: |
        dig php
        curl php
