name: php_container

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: php:latest
      ports:
      - 80
    steps:
    - name: curl
      run: curl localhost
