name: push_tags_with_underscore

on:
  push:
    tags:
      - '[a-z0-9_]+-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
