name: pr_path2

on:
  pull_request:
    branches: [develop]
    paths: ['path2/**']
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo '${{ toJSON(github) }}'
