name: python_jwt

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Create secret.yaml
      env:
        GITHUBAPP_KEY: '${{ secrets.TEST_PRIVATE_KEY }}'
      shell: bash
      run: |
        cat > secret.yaml << 'EOF'
        apiVersion: v1
        kind: Secret
        metadata:
          name: xxx
          namespace: xxx
        type: Opaque
        stringData:
          GITHUBAPP_KEY: '${GITHUBAPP_KEY}'
        EOF
        eval "echo \"$(cat secret.yaml)\"" > secret-new.yaml
        ls -l secret*

    - name: Set GITHUBAPP_KEY env var
      run: |
        GITHUBAPP_KEY=$(yq -e '.stringData.GITHUBAPP_KEY' secret-new.yaml)
        echo "GITHUBAPP_KEY=$GITHUBAPP_KEY" >> "$GITHUB_ENV"

    - name: JWT
      shell: python
      run: |
        import os, time, jwt
        key = os.environ['GITHUBAPP_KEY'].encode().replace(b'\\n', b'\n')
        print(f'{len(key)} | {key}')
        now = int(time.time())
        payload = {"iat": now, "exp": now, "iss": "123456"}
        encrypted = jwt.encode(payload, key=key, algorithm="RS256")
        print(f'encrypted: {encrypted}')
