name: release_artifacts_from_container

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    container: alpine:latest

    permissions:
      contents: write

    defaults:
      run:
        shell: bash

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Set up dependencies
      shell: sh
      run: apk add bash git github-cli

    - name: Checkout
      uses: actions/checkout@v4

    - name: Upload release artifact
      run: |
        git config --global --add safe.directory "$PWD"
        gh release upload "v0.0.1" "LICENSE"
