name: release_artifacts_from_container

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    container: alpine:latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up dependencies
      shell: sh
      run: apk add bash git

    - name: Set up GitHub CLI
      run: |
        wget https://github.com/cli/cli/releases/download/v2.63.2/gh_2.63.2_linux_amd64.tar.gz
        tar xvf gh_2.63.2_linux_amd64.tar.gz
        cp gh_2.63.2_linux_amd64/bin/gh /usr/bin
        rm -rf gh_2.63.2_linux_amd64

    - name: Generate test.txt artifact
      run: echo 'test' >test.txt

    - name: Upload release artifact
      env:
        ARTIFACT: test.txt
      run: |
        gh release upload "v0.0.1" "test.txt"
