name: rust_hello_world_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and run tests
      run: |
        cd rust/hello_world
        cargo build --verbose
        cargo run
        cargo test --verbose
