name: runner_context

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Dump runner context
      run: |
        echo '${{ toJson(runner) }}' >> "$GITHUB_STEP_SUMMARY"

    - name: Dump github context
      run: |
        echo '${{ toJson(github) }}' >> "$GITHUB_STEP_SUMMARY"
