name: reviewdog_test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v3

      - name: Run detect-secrets with reviewdog
        uses: reviewdog/action-detect-secrets@v0.11.6
