name: slack_test

on: workflow_dispatch

jobs:
  slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          slack_payload.json

    - name: Set env vars
      env:
        GITHUB_EVENT_HEAD_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
      uses: iamazeem/substitute-action@v1
      with:
        input-files: |
          slack_payload.json

    - name: Dump payload file
      run: cat slack_payload.json

    - name: Send message to Slack
      uses: slackapi/slack-github-action@v2
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload-file-path: slack_payload.json
