name: solaris_11_vcpkg

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Solaris 11
      uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install git gcc
        run: |
          pwd
          ls -lah
          whoami
          cat /etc/release
          git --version
          gcc --version
