name: supabase_services_container

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: supabase/postgres:15.6.1.133
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
          POSTGRES_HOST_AUTH_METHOD: host
        ports:
        - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Install postgresql-client (psql)
        run: |
          sudo apt update -y
          sudo apt install -y postgresql-client
          psql --version

      - name: Check
        run: |
          psql "postgresql://postgres:postgres@localhost:5432/test_db" <<EOF
            CREATE TABLE test (id INT);
            INSERT INTO test (id) VALUES (123);
            INSERT INTO test (id) VALUES (456);
            INSERT INTO test (id) VALUES (789);
            SELECT * FROM test;
          EOF
