name: solaris_11_vcpkg

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Solaris 11
      uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install git gcc
        run: |
          git --version
          gcc --version

          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh

          # export VCPKG_ROOT=/path/to/vcpkg
          # export PATH=$VCPKG_ROOT:$PATH

          ./vcpkg install zlib
