name: secret_multiline_string

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      env:
        STR1: ${{ secrets.MULTILINE }}
        STR2: '${{ secrets.MULTILINE }}'
        STR3: >-
          ${{ secrets.MULTILINE }}
      run: |
        echo "STR1: [$STR1]"
        echo "STR2: [$STR2]"
        echo "STR3: [$STR3]"
