name: solaris_11_vcpkg

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Solaris 11
      uses: vmactions/solaris-vm@v1
      with:
        copyback: false
        usesh: true
        prepare: |
          pkg install git gcc tar
        run: |
          alias tar=gtar
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install zlib
