name: slack_test

on: workflow_dispatch

jobs:
  set-payload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          slack_payload.json

    - name: Upload payload file
      uses: actions/upload-artifact@v4
      with:
        name: slack_payload
        path: slack_payload.json

  send-message:
    needs: set-payload
    runs-on: ubuntu-latest

    steps:
    - name: Download payload file
      uses: actions/download-artifact@v4
      with:
        name: slack_payload

    - name: Send message to Slack
      uses: slackapi/slack-github-action@v2
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload-file-path: slack_payload.json
        payload-templated: true
