name: secrets_to_env

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set
      run: |
        echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k] | @base64)"' >> "$GITHUB_ENV"

    - name: Get
      run: |
        base64 -d <<< "$github_token"
        base64 -d <<< "$TEST"
        base64 -d <<< "$TEST_DEPLOY_KEY"
