name: secret_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh --version
        gh secret list
