name: vars_to_env

on: workflow_dispatch

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     ACTION_DIR: ${{ steps.set-dir.outputs.ACTION_DIR }}
  #   steps:
  #     - name: Set output
  #       id: set-dir
  #       run: echo "ACTION_DIR=set-env-vars-from-json" >> $GITHUB_OUTPUT

  ci:
    # needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set vars to env
      # uses: ./.github/actions/${{ needs.setup.outputs.ACTION_DIR }}
      uses: ./.github/actions/set-env-vars-from-json
      with:
        json: '${{ toJSON(vars) }}'

      # env:
      #   VARS_JSON: ${{ toJSON(vars) }}
      # run: |
      #   echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV

    - name: Check env vars
      run: |
        echo "VAR1=$VAR1"
        echo "VAR2=$VAR2"
