name: vars_to_env

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Set vars to env
      env:
        VARS_JSON: '${{ toJSON(vars) }}'
      run: |
        echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > .env
        cat .env >> $GITHUB_ENV

    - name: Check env vars
      run: |
        env | grep VAR
