name: wd_test

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "TAG"
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      env:
        TAG: ${{ inputs.tag_name }}
      run: echo "$TAG"
