name: workflow_dispatch

env:
  options: '["A","B","C"]'

on:
  workflow_dispatch:
    inputs:
      options:
        description: 'Options'
        required: true
        type: choice
        options: ${{ fromJSON(env.options) }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "Test"
