name: win_excel_com_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Setup
        run: |
          choco install office365business
          pip install pywin32
          python --version

      - name: Run Python script
        shell: python
        run: |
          import os
          import win32com.client as win32

          excel = win32.Dispatch("Excel.Application")
          workbook = excel.Workbooks.Add()
          workbook.SaveAs(os.getcwd() + '\\Created.xlsx')
          workbook.Close()
          excel.Quit()

      - name: Check
        shell: bash
        run: ls -hl
