name: win_excel_com_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - name: Create
      env:
        SCRIPT: |
          import os
          import win32com.client as win32
          
          excel = win32.Dispatch("Excel.Application")
          workbook = excel.Workbooks.Add()
          workbook.SaveAs(os.getcwd() + '\\Created.xlsx')
          workbook.Close()
          excel.Quit()
      run: |
        echo $SCRIPT > excel.py
        python --version
        python excel.py
        ls
