name: win_proto_convert_test

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        repository: iamazeem/proto-convert

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
        bundler-cache: true

    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Install protoc
      uses: arduino/setup-protoc@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and install
      run: |
        gem build *.gemspec
        gem install *.gem
        proto-convert -h
        echo "proto-convert installed successfully"

    - name: Test
      run: |
        pwd
        ls -l
        ./test/run_tests.sh
