name: share_output_bw_jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Set output
        id: data-step
        shell: bash
        run: echo "DATA='message'" >> $GITHUB_OUTPUT

  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Get output
        shell: bash
        run: echo "DATA=${{ needs.job1.data-step.outputs.DATA }}"
