name: win_custom_shell

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    # - name: Install yq
    #   run: choco install yq

    - name: Create sample YAML file
      shell: bash
      env:
        YAML: |
          name: test
          version: 1.2.3
          homepage: https://example.com/test
          documentation: https://example.com/test/docs
          environment:
            sdk: '>=2.12.0 <3.0.0'
      run: echo "$YAML" > pubspec.yaml && cat pubspec.yaml

    - name: Get version with yq action
      id: yq
      uses: mikefarah/yq@master
      with:
        cmd: yq -r '.version' 'pubspec.yaml'

    # - name: Set version
    #   run: |
    #     yq -r .version pubspec.yaml > version.file
    #     set /p VERSION=<version.file
    #     echo VERSION: %VERSION%
    #     echo VERSION=%VERSION% >> %GITHUB_ENV%

    - name: Print version
      run: echo VERSION=${{ steps.yq.outputs.result }}
