name: win_excel_com_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - name: Checkout [${{ github.repository }}]
      uses: actions/checkout@v4

    - name: Setup Python 3.12.3
      uses: actions/setup-python@v6
      with:
        python-version: '3.12.3'

    - name: Install Office 365 Business
      run: choco install office365business --params "'/productid:ExcelRetail /updates:FALSE'"

    - name: Install pywin32 
      run: pip install pywin32 ImageGrab pillow

    - name: Generate PNG [smaple.xlsx]
      shell: python
      run: |
        import os
        import win32com.client as win32
        from PIL import ImageGrab

        input_file = os.path.join(os.getcwd(), "sample.xlsx")
        output_file = os.path.join(os.getcwd(), "sample.png")

        try:
          excel = win32.Dispatch("Excel.Application")
          excel.Visible = False
          workbook = excel.Workbooks.Open(input_file, ReadOnly=True)
          worksheet = workbook.Worksheets("Sheet1")
          range = worksheet.UsedRange
          range.CopyPicture(Appearance=1, Format=2)
          workbook.Close(SaveChanges=False)
          excel.Quit()

          image = ImageGrab.grabclipboard()
          if image is None:
            print("[ERR] Image not found in clipboard!")
          else:
            image.save(output_file, "PNG")
            print("[ERR] Image saved successfully!")
        except Exception as e:
          print("[ERR] Failed to export image!")
          raise e

    - name: Generate PNG [sample2.xlsx (Input + Equipment) => sample2.png]
      shell: python
      run: |
        import os
        import win32com.client as win32
        from PIL import ImageGrab

        input_file = os.path.join(os.getcwd(), "sample2.xlsx")
        output_file = os.path.join(os.getcwd(), "sample2.png")

        try:
          excel = win32.Dispatch("Excel.Application")
          excel.Visible = False
          workbook = excel.Workbooks.Open(input_file, ReadOnly=True)
          worksheet = workbook.Worksheets("Input + Equipment")
          range = worksheet.UsedRange
          range.CopyPicture(Appearance=1, Format=2)
          workbook.Close(SaveChanges=False)
          excel.Quit()

          image = ImageGrab.grabclipboard()
          if image is None:
            print("[ERR] Image not found in clipboard!")
          else:
            image.save(output_file, "PNG")
            print("[ERR] Image saved successfully!")
        except Exception as e:
          print("[ERR] Failed to export image!")
          raise e

    - name: Check
      shell: bash
      run: ls -Gghl sample*.png

    - name: Upload [sample.png]
      uses: actions/upload-artifact@v5
      with:
        name: sample.png
        path: sample.png
        if-no-files-found: error

    - name: Upload [sample2.png (Input + Equipment)]
      uses: actions/upload-artifact@v5
      with:
        name: sample2.png
        path: sample2.png
        if-no-files-found: error
