name: win_custom_shell

on: workflow_dispatch

jobs:
  ci:
    steps:
    - name: Set version
      shell: cmd
      run: |
        set VERSION='1.2.3'
        echo "VERSION: %VERSION%"
        echo "VERSION=%VERSION%" >> "$GITHUB_ENV"

    - name: Get version
      shell: cmd
      run: |
        echo ${{ env.VERSION }}
        echo "VERSION: %VERSION%"
