name: win_custom_shell

on: workflow_dispatch

defaults:
  run:
    shell: powershell

jobs:
  ci:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
    - name: Install yq
      run: choco install yq

    - name: Create sample YAML file
      shell: bash
      env:
        YAML: |
          name: test
          version: 1.2.3
          homepage: https://example.com/test
          documentation: https://example.com/test/docs
          environment:
            sdk: '>=2.12.0 <3.0.0'
      run: echo "$YAML" > pubspec.yaml && cat pubspec.yaml

    # - name: Get version with yq action
    #   id: yq
    #   uses: mikefarah/yq@master
    #   with:
    #     cmd: yq -r '.version' 'pubspec.yaml'

    - name: Set version
      run: |
        $VERSION=(yq -r .version pubspec.yaml)
        echo VERSION: $VERSION
        echo VERSION=$VERSION | Out-File -FilePath $ENV:GITHUB_ENV -Append

    # - name: Print version
    #   run: echo VERSION=${{ steps.yq.outputs.result }}

    - name: Print version
      run: echo VERSION=${{ env.VERSION }}
