name: win_mingw_test

on: workflow_dispatch

jobs:
  ci:
    name: CI
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      env:
        JOB_ID: ${{ github.job }}
        JOB_NAME: ${{ jobs.ci.name }}
      shell: bash
      run: |
        echo "JOB_ID: $JOB_ID"
        echo "JOB_NAME: $JOB_NAME"
        gcc --version
        g++ --version
        gcc test.c -o test_c && ./test_c
        g++ test.cpp -o test_cpp && ./test_cpp
