name: win_excel_com_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install Office
      run: choco install office365business --params "'/productid:ExcelRetail /updates:FALSE'"

    - name: Install pywin32 
      run: pip install pywin32

    - name: Run Python script
      shell: python
      run: |
        import os
        import win32com.client as win32

        excel = win32.Dispatch("Excel.Application")
        workbook = excel.Workbooks.Add()
        workbook.SaveAs(os.getcwd() + '\\Created.xlsx')
        workbook.Close()
        excel.Quit()

    - name: Check
      shell: bash
      run: ls -hl
