name: win_excel_com_test

on: workflow_dispatch

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Install Office
        run: choco install office365business

      - name: Set up script
        env:
          SCRIPT: |
            import os
            import win32com.client as win32

            excel = win32.Dispatch("Excel.Application")
            workbook = excel.Workbooks.Add()
            workbook.SaveAs(os.getcwd() + '\\Created.xlsx')
            workbook.Close()
            excel.Quit()
        run: |
          pip install pywin32
          echo $env:SCRIPT > excel.py
          python --version

      - name: Run script
        run: |
          python excel.py
          ls
