name: win_custom_shell

on: workflow_dispatch

defaults:
  run:
    shell: cmd

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - name: Install yq
      run: choco install yq

    - name: Create sample YAML file
      shell: bash
      env:
        YAML: |
          name: test
          version: 1.2.3
          homepage: https://example.com/test
          documentation: https://example.com/test/docs
          environment:
            sdk: '>=2.12.0 <3.0.0'
      run: echo "$YAML" > pubspec.yaml && cat pubspec.yaml

    - name: Set version
      run: |
        yq -r .version pubspec.yaml > version.file
        set /p VERSION=<version.file
        echo VERSION: %VERSION%
        echo VERSION=%VERSION% >> %GITHUB_ENV%

    - name: Get version
      run: |
        echo VERSION=%VERSION%
        echo VERSION=${{ env.VERSION }}
