name: share_output_bw_jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    outputs:
      data: ${{ steps.set-data.outputs.DATA }}
    steps:
      - name: Set output
        id: set-data
        run: echo "DATA=message" >> $ENV:GITHUB_OUTPUT

  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Get output
        env:
          DATA: ${{ needs.job1.outputs.data }}
        run: echo "DATA=$ENV:DATA"
