name: wd_test_runner

on: workflow_dispatch

permissions:
  actions: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: "v0.0.0"
      run: |
        gh --version
        gh workflow run ci-wd-test.yml -f tag_name="$TAG" --repo iamazeem/test
