name: win_custom_shell

on: workflow_dispatch

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - name: Step 1 (cmd)
      shell: cmd
      run: |
        chcp 65001
        echo TEST1=cmd >> %GITHUB_ENV%
        echo TEST2=cmd >> %GITHUB_ENV%

    - name: Step 2 (cmd)
      shell: cmd
      run: |
        echo TEST1=%TEST1%
        echo TEST2=%TEST2%
        echo env.TEST1=${{ env.TEST1 }}
        echo env.TEST2=${{ env.TEST2 }}

    # - name: Step 3 (pwsh)
    #   run: |
    #     echo "GITHUB_ENV: $ENV:GITHUB_ENV"
    #     type $ENV:GITHUB_ENV
    #     echo "TEST=pwsh" | Out-File -FilePath $ENV:GITHUB_ENV -Append

    # - name: Step 4 (pwsh)
    #   run: |
    #     echo "GITHUB_ENV: $ENV:GITHUB_ENV"
    #     type $ENV:GITHUB_ENV
    #     echo "TEST=$ENV:TEST"
    #     echo "env.TEST=${{ env.TEST }}"

    # - name: Step 5 (bash)
    #   shell: bash
    #   run: |
    #     echo "GITHUB_ENV: $GITHUB_ENV"
    #     cat $GITHUB_ENV
    #     echo "TEST=bash" >> $GITHUB_ENV

    # - name: Step 6 (bash)
    #   shell: bash
    #   run: |
    #     echo "GITHUB_ENV: $GITHUB_ENV"
    #     cat $GITHUB_ENV
    #     echo "TEST=$TEST"
    #     echo "env.TEST=${{ env.TEST }}"
