name: share_output_bw_jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    outputs:
      data: ${{ steps.set-data.outputs.DATA }}
    steps:
      - name: Set output
        id: set-data
        shell: bash
        run: echo "DATA='message'" >> $GITHUB_OUTPUT

  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Get output
        shell: bash
        env:
          DATA: ${{ needs.job1.outputs.DATA }}
        run: echo "DATA=${{ env.DATA }}"
