name: win_step_summary

on: workflow_dispatch

jobs:
  win-add-content:
      runs-on: windows-latest
      steps:
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "# Heading"
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Item  1"
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Item  2"
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Item  3"

  win-out-file:
    runs-on: windows-latest
    steps:
    - run: '"# Heading" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'
    - run: '"- Item  1" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'
    - run: '"- Item  2" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'
    - run: '"- Item  3" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'

  win-bash:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - run: echo "# Heading" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  1" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  2" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  3" >> "$GITHUB_STEP_SUMMARY"

  ubuntu-bash:
    runs-on: ubuntu-latest
    steps:
    - run: echo "# Heading" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  1" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  2" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  3" >> "$GITHUB_STEP_SUMMARY"

  macos-bash:
    runs-on: macos-latest
    steps:
    - run: echo "# Heading" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  1" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  2" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  3" >> "$GITHUB_STEP_SUMMARY"
