name: zsv_on_macos

on: workflow_dispatch

jobs:
  ci:
    strategy:
      matrix:
        # os: [macos-13, macos-14]
        os: [macos-14]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - name: Check xcode version
      run: |
        xcodebuild -version
        sudo rm -rf /Applications/Xcode*.app
        xcodebuild -version || true

    - name: Tap and install
      run: |
        brew tap liquidaty/zsv
        brew install zsv
    
    - name: Check installed version
      run: zsv version

    - name: Uninstall and untap
      run: |
        brew uninstall zsv
        brew untap liquidaty/zsv
        zsv version || true

  # ci:
  #   strategy:
  #     matrix:
  #       os: [macos-14]

  #   runs-on: ${{ matrix.os }}

  #   env:
  #     TAG: "0.0.0"
  #     ARM64_MACOSX_GCC: arm64-macosx-gcc
  #     ARTIFACT_DIR: .artifacts
  #     ARTIFACT_RETENTION_DAYS: 5

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       repository: liquidaty/zsv

  #   - name: Install deps
  #     run: |
  #       brew install coreutils tree autoconf automake libtool

  #   - name: Build on macOS (${{ env.ARM64_MACOSX_GCC }})
  #     if: matrix.os == 'macos-14'
  #     env:
  #       PREFIX: ${{ env.ARM64_MACOSX_GCC }}
  #       CC: gcc-11
  #       MAKE: make
  #       RUN_TESTS: false
  #     shell: bash
  #     run: |
  #       ./scripts/ci-build.sh
  #       ./$PREFIX/bin/zsv version

  #   - name: Prepare build artifacts for upload
  #     run: ./scripts/ci-prepare-artifacts-for-upload.sh

  #   - name: Upload (zsv-${{ env.TAG }}-${{ env.ARM64_MACOSX_GCC }}.zip)
  #     if: matrix.os == 'macos-14'
  #     uses: actions/upload-artifact@v4
  #     env:
  #       ARTIFACT_NAME: zsv-${{ env.TAG }}-${{ env.ARM64_MACOSX_GCC }}.zip
  #     with:
  #       name: ${{ env.ARTIFACT_NAME }}
  #       path: ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}
  #       retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
  #       if-no-files-found: error

  #   - name: Upload (zsv-${{ env.TAG }}-${{ env.ARM64_MACOSX_GCC }}.tar.gz)
  #     if: matrix.os == 'macos-14'
  #     uses: actions/upload-artifact@v4
  #     env:
  #       ARTIFACT_NAME: zsv-${{ env.TAG }}-${{ env.ARM64_MACOSX_GCC }}.tar.gz
  #     with:
  #       name: ${{ env.ARTIFACT_NAME }}
  #       path: ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}
  #       retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
  #       if-no-files-found: error
