name: zsv_on_macos_fuzz

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: liquidaty/zsv
        ref: underflow-fix-v2

    - name: Install deps
      run: |
        brew update
        brew install coreutils afl++

    - name: Run fuzzing
      env:
        AFL_DEBUG: 1
      run: |
        sudo afl-system-config

        cd fuzz
        make afl-build

        mkdir -p afl/optimized/.traces

        echo
        echo "=== Running afl-showmap ==="
        # afl-showmap -e -m none -t 5000 -o /dev/null -Z -- ./afl/fuzz < ../data/test/2tsv-2.csv
        afl-showmap -e -m none -t 5000 -o /dev/null -Z -- ./afl/fuzz <

        echo
        echo "=== Running ./afl/fuzz with 2tsv-2.csv ==="
        ./afl/fuzz < ../data/test/2tsv-2.csv

        echo
        echo "=== Running afl-cmin.bash ==="
        unset AFL_DISABLE_LLVM_INSTRUMENTATION
        afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"

        # echo "=== afl-run ==="
        # make afl-run

        # echo "=== Running afl-cmin ==="
        # afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"

        # echo "=== Running afl-fuzz ==="
        # mkdir -p afl/out
        # afl-fuzz -u -i ../data/test -x csv.dict -o ./afl/out -- ./afl/fuzz
