name: zsv_on_macos_fuzz

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: liquidaty/zsv
        ref: underflow-fix-v2

    - name: Install deps
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          {
            echo "/home/linuxbrew/.linuxbrew/bin"
            echo "/home/linuxbrew/.linuxbrew/opt/coreutils/libexec/gnubin"
          } >> "$GITHUB_PATH"
        fi
        brew update
        brew install coreutils afl++

    - name: Config system for afl
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo /home/linuxbrew/.linuxbrew/bin/afl-system-config
        else
          sudo afl-system-config
        fi

    - name: Repro crash
      run: |
        cd fuzz
        make afl-repro-crash CRASH_FILE=./misc/id:000000,sig:06,src:001129,time:1545512,execs:22534629,op:havoc,rep:15

    # - name: Run fuzzing
    #   id: fuzz
    #   env:
    #     # AFL_DEBUG: 1
    #     AFL_NO_FORKSRV: 1
    #   run: |
    #     cd fuzz
    #     make afl-run-parallel STOP_ON_CRASH=1 TIMEOUT_SECONDS=10800
    #     make afl-show-progress-summary ALL=1

    # - name: Collect afl crashes
    #   if: always()
    #   id: crashes
    #   run: |
    #     cd fuzz
    #     make afl-list-crashes | tee -a "$GITHUB_STEP_SUMMARY"
    #     {
    #       echo "CRASH_COUNT=$(make afl-list-crashes | wc -l)"
    #       echo "CRASH_FILES<<EOF
    #       $(make afl-list-crashes)
    #       echo "EOF"
    #     } >>"$GITHUB_OUTPUT"

    # - name: Upload artifacts
    #   if: ${{ steps.crashes.outputs.CRASH_COUNT != '0' }}
    #   uses: actions/upload-artifact@v7
    #   with:
    #     name: afl-crashes-${{ matrix.os }}
    #     path: |
    #       ${{ steps.crashes.outputs.CRASH_FILES }}
