name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: rui314/setup-mold@v1
        with:
          mold-version: 1.1.1

      - name: Create mold symlink [ld -> mold]
        run: |
          sudo ln -sf /usr/local/bin/mold $(realpath /usr/bin/ld)
          echo '--- [DONE] ---'

      - name: Run script
        run: |
          echo 'Testing...'
          go env
          which ld
          whereis ld
          realpath /usr/bin/ld
          ld --version
          echo '--- [DONE] ---'
