name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Verify ccache and update GITHUB_PATH
        run: |
          which ccache
          ccache --version
          #export PATH="/usr/lib/ccache:$PATH"
          echo '/usr/lib/ccache' >> $GITHUB_PATH
          which gcc
          echo '--- [DONE] ---'

      - uses: rui314/setup-mold@2a0eac129273d80a0511fcf8aa9d1986fafa16d2
        with:
          mold-version: 1.1.1

      - name: Run script
        run: |
          echo 'Testing...'
          which gcc
          go env
          which ld
          whereis ld
          realpath /usr/bin/ld
          ld --version
          echo '--- [DONE] ---'
