name: Test  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo Testing!

      - uses: 8398a7/action-slack@v3
        if: github.ref == 'refs/heads/main'
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
          fields: all
          if_mention: success,failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
