name: reusable_workflow_caller

on:
  workflow_dispatch:

env: 
  BRANCH: ${{ github.head_ref }}

jobs:
  set-env-vars:
    uses: ./.github/workflows/reusable_workflow_set_env_vars.yml@main
    with:
      env_vars: |
        TEST_VAR_1=testing
        TEST_VAR_2="testing again..."
        BRANCH_1=${{ env.BRANCH }}
        BRANCH_2="$GITHUB_REF"
        BRANCH_3=$GITHUB_REF
