name: reusable_workflow_set_output

on:
  workflow_call:
    outputs:
      test:
        value: '${{ jobs.set.outputs.test }}'

jobs:
  set:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    outputs:
      test: '${{ steps.set.outputs.test }}'

    steps:
    - name: Set
      id: set
      run: |
        $output="test=123"
        echo "output: $output"
        echo $output >> $env:GITHUB_OUTPUT

    - name: Get
      run: |
        echo "test: ${{ steps.set.outputs.test }}"
