name: reusable_workflow_2_set_output_caller
run-name: caller

on: workflow_dispatch

jobs:
  set:
    name: callee
    uses: ./.github/workflows/reusable_workflow_2_set_output_callee.yml

  get:
    name: caller-get
    needs: set
    runs-on: ubuntu-latest

    steps:
    - name: Get
      run: |
        echo "success=${{ needs.set.outputs.success }}"
        echo "failure=${{ needs.set.outputs.failure }}"

    - name: Compare
      env:
        SUCCESS: ${{ needs.set.outputs.success == 'true' && 'OK' || 'NOK' }}
        FAILURE: ${{ needs.set.outputs.failure == 'true' && 'OK' || 'NOK' }}
      run: |
        {
          echo "SUCCESS=$SUCCESS"
          echo "FAILURE=$FAILURE"
        } | tee -a "$GITHUB_STEP_SUMMARY"
