name: reusable_workflow_set_env_vars

on:
  workflow_call:
    inputs:
      env_vars:
        required: true
        type: string
        description: list of vars and values

jobs:
  set-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      if: ${{ inputs.env_vars }}
      run: |
        for VAR in ${{ inputs.env_vars }}; do
          echo "$VAR"
          # echo "$VAR" >> $GITHUB_ENV
        done

    - name: Get environment variables
      if: ${{ inputs.env_vars }}
      run: |
        for VAR in "${{ inputs.env_vars }}"; do
          KEY=$(echo "$VAR" | cut -d '=' -f1)
          echo "KEY: $KEY"
          echo "VAL: ${!KEY}"
        done
