name: reusable_workflow_set_env_vars

on:
  workflow_call:
    inputs:
      env_vars:
        required: true
        type: string
        description: list of vars and values

jobs:
  set-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      if: ${{ inputs.env_vars }}
      run: |
        for VAR in "${{ inputs.env_vars }}"; do
          echo -e "[$VAR]"
          echo -n "$VAR" >> $GITHUB_ENV
        done

    - name: Get environment variables
      if: ${{ inputs.env_vars }}
      run: |
        for VAR in "${{ inputs.env_vars }}"; do
          KEY=$(echo -n "$VAR" | cut -d '=' -f1)
          echo -e "KEY: [$KEY]"
          echo -e "VAL: [${!KEY}]"
        done
