name: reusable_workflow_2_set_output_callee
run-name: callee

on:
  workflow_call:
    outputs:
      success:
        value: ${{ jobs.set.outputs.success }}
      failure:
        value: ${{ jobs.set.outputs.failure }}
      complete:
        value: ${{ jobs.set.outputs.complete }}

jobs:
  set:
    runs-on: ubuntu-latest

    outputs:
      # success: ${{ steps.set.outputs.success }}
      # failure: ${{ steps.set.outputs.failure }}
      success: ${{ steps.set.outcome  == 'success' }}
      failure: ${{ steps.set.outcome  == 'failure' }}
      complete: |
        ${{
          steps.set.outcome  == 'success' &&
          steps.get.outcome  == 'success' &&
          steps.fail.outcome == 'failure'
        }}

    steps:
    - name: Set
      id: set
      run: |
        {
          echo "success=true"
          echo "failure=false"
        } | tee -a "$GITHUB_OUTPUT" "$GITHUB_STEP_SUMMARY"

    - name: Get
      id: get
      run: |
        echo "success=${{ steps.set.outputs.success }}"
        echo "failure=${{ steps.set.outputs.failure }}"

    - name: Fail
      id: fail
      continue-on-error: true
      run: exit 1

    - name: Fail Status
      run: echo '${{ steps.fail.outcome }}'
