name: reusable_workflow_caller

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        type: string
        required: true
        default: 'NAME'

jobs:
  # set-env-vars:
  #   uses: ./.github/workflows/reusable_workflow_set_env_vars.yml
  #   with:
  #     env_vars: |
  #       TEST_VAR=test-var
  #       GITHUB_HEAD_REF=$GITHUB_HEAD_REF
  #       GITHUB_WORKSPACE=$GITHUB_WORKSPACE
  #       GITHUB_REF=$GITHUB_REF

  test-name:
    name: test
    uses: ./.github/workflows/reusable_workflow_set_env_vars.yml
    with:
      inputs: ${{ toJSON(inputs) }}
