name: reusable_workflow_set_env_vars

on:
  workflow_call:
    inputs:
      env_vars:
        required: true
        type: string
        description: list of vars and values

jobs:
  set-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: set environment variables
      if: ${{ inputs.env_vars }}
      env:
        ENV_VARS: ${{ inputs.env_vars }}
      run: |
        for env in $ENV_VARS; do
          echo "env: $env"
          echo "--- --- --- ---"
          # printf "%s\n" $env >> $GITHUB_ENV
        done
