name: reusable_workflow_set_env_vars

on:
  workflow_call:
    inputs:
      # env_vars:
      #   required: true
      #   type: string
      #   description: list of vars and values
      inputs:
        description: inputs
        required: false
        type: string

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Check
      run: |
        echo '${{ toJson(fromJson(inputs.inputs)) }}'
        echo "$USER"

    # - name: Set environment variables
    #   if: ${{ inputs.env_vars }}
    #   run: |
    #     IFS=$'\n'
    #     for VAR in ${{ inputs.env_vars }}; do
    #       echo -e "VAR: [$VAR]"
    #       echo -n "$VAR" >> $GITHUB_ENV
    #       # export $VAR
    #     done

    # - name: Get environment variables
    #   if: ${{ inputs.env_vars }}
    #   run: |
    #     IFS=$'\n'
    #     for VAR in ${{ inputs.env_vars }}; do
    #       KEY=$(echo -n "$VAR" | cut -d '=' -f1)
    #       echo -e "[$KEY] => [${!KEY}]"
    #     done
