name: reusable_workflow_2_set_output_caller

on: workflow_dispatch

jobs:
  set:
    uses: ./.github/workflows/reusable_workflow_2_set_output_callee.yml

  get:
    needs: set
    runs-on: ubuntu-latest

    steps:
    - name: Get
      run: |
        echo "success=${{ steps.set.outputs.success }}"
        echo "failure=${{ steps.set.outputs.failure }}"
